on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install flake8 isort
    - name: linters
      run: |
        flake8
        isort -c mfa
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.7'
            django: '3.2'
          - python: '3.10'
            django: '4.0'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - run: pip install . coverage "django==${{ matrix.django }}"
    - name: tests
      run: |
        coverage run -m tests.manage test
        coverage report
