on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install flake8 isort
    - name: linters
      run: |
        flake8
        isort -c mfa
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']
        django-version: ['2.2', '3.2', '4.0']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install . coverage "django==${{ matrix.django-version }}"
    - name: tests
      run: |
        coverage run -m tests.manage test
        coverage report
